apiVersion: emp.cluster.com/v1alpha1
kind: KafkaACL
metadata:
  name: my-kafka-acl-cl-v1
  namespace: confluent
spec:
  principal: "User:acl-test"
  resourceType: "TOPIC"
  resourceName:
    - "tef.de.testing-v1"
    - "tef.de.testing-v2"
  operation: ["WRITE"]
  permissionType: "ALLOW"
  patternType: "LITERAL"
