apiVersion: kafka.namespaced.com/v1alpha1
kind: KafkaACL
metadata:
  name: my-kafka-acl-ns
  namespace: confluent
spec:
  principal: "User:foo"
  resourceType: "TOPIC"
  resourceName: "tef.de.topas.BarringEvents-MM-v1"
  operation: "READ"
  permissionType: "ALLOW"
  patternType: "LITERAL"
