apiVersion: emp.namespaced.com/v1alpha1
kind: KafkaACL
metadata:
  name: my-kafka-acl-ns
  namespace: wowsome
spec:
  principal: "User:wow"
  resourceType: "TOPIC"
  resourceName:
    - "tef.de.testing-v1"
    - "tef.de.testing-v2"
    - "tef.de.testing-v3"
  operation: "READ"
  permissionType: "ALLOW"
  patternType: "LITERAL"
