apiVersion: v1
kind: Pod
metadata:
  name: acl-app
  labels:
    app: acl-app
spec:
  containers:
  - name: acl-app
    image: mdwajid095/kafka-acl-operator:v1
    imagePullPolicy: Always
    command: ["sleep", "infinity"]
    env:
    - name: NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: ADM_PROPERTIES_PATH
      value: /mnt/sslcerts/adm.properties
    - name: REST_URL
      value: http://kafka.wowsome.svc.cluster.local:8090
    - name: CLUSTER_ID
      value: QNCeE1QyS1yGuW6_Vb3VRwow
    volumeMounts:
    - name: acl-operator-properties
      mountPath: /mnt/sslcerts
  volumes:
  - name: acl-operator-properties
    secret:
      secretName: acl-operator-secret
