# values for acl operator
image:
  repository: mdwajid095/kafka-acl-operator 
  pullPolicy: Always
  tag: "v1"

secret:
  name: acl-operator-secret
  path: /mnt/sslcerts

# ENV is mandatory for acl-operator
env:
  ADM_PROPERTIES_PATH: /mnt/sslcerts/adm.properties
