apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: kafkaacls.emp.cluster.com
spec:
  group: emp.cluster.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                principal:
                  type: string
                resourceType:
                  type: string
                resourceName:
                  type: array
                  items:
                    type: string
                operation:
                  type: array
                  items:
                    type: string
                permissionType:
                  type: string
                patternType:
                  type: string
  scope: Cluster
  names:
    plural: kafkaacls
    singular: kafkaacl
    kind: KafkaACL
    shortNames:
      - acls
