{{- range .Values.kafkaACL }}
apiVersion: emp.namespaced.com/v1alpha1
kind: KafkaACL
metadata:
  name: {{ include "generateName" . }}
  namespace: {{ default $.Values.defaults.namespace .namespace }}
  labels:
    emp.telefonica.de/bus: {{ .bus | quote }}
    {{- include "emp-acl.labels" $ | nindent 4 }}
spec:
  principal: {{ .principal | quote}}
  resourceType: {{ default $.Values.defaults.resourceType .resourceType }}
  resourceName:
    {{- range .resourceName }}
    - {{ . }}
    {{- end }}
  operation:
    {{- range .operation }}
    - {{ . }}
    {{- end }}
  permissionType: {{ default $.Values.defaults.permissionType .permissionType }}
  patternType: {{ default $.Values.defaults.patternType .patternType }}
---
{{- end }}
