{{- range .Values.kafkaACL }}
apiVersion: kafka.namespaced.com/v1alpha1
kind: KafkaACL
metadata:
  name: {{ include "generateName" . }}
  namespace: {{ default $.Values.defaults.namespace .namespace }}
  labels:
    {{- include "kafka-acl.labels" $ | nindent 4 }}
spec:
  principal: {{ .principal }}
  resourceType: {{ default $.Values.defaults.resourceType .resourceType }}
  resourceName: {{ .resourceName }}
  operation: {{ .operation }}
  permissionType: {{ default $.Values.defaults.permissionType .permissionType }}
  patternType: {{ default $.Values.defaults.patternType .patternType }}
---
{{- end }}
